bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Praveen Raj, Maxime U Garcia
  description: GATK4 RNA variant calling pipeline
  force: false
  is_nfcore: true
  name: rnavar
  org: nf-core
  outdir: .
  skip_features: null
  version: 2.0.0dev
update: null
